version: "3"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
    ports:
      - 3307:3306
    volumes:
      - mysql5.7:/var/lib/mysql
    networks:
      - tirnado

  redis:
    image: redis:latest
    networks:
      - tirnado

  tornado:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.test
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - redis
    networks:
      - tirnado

volumes:
  mysql5.7:

networks:
  tirnado:
    driver: bridge

